-- Personal exceptions to Omarchy's bindings; all other bindings stay upstream.
hl.unbind("SUPER + W")
o.bind("SUPER + Q", "Close window", hl.dsp.window.close())
hl.unbind("SUPER + RETURN")
o.bind("SUPER + RETURN", "Ghostty", "ghostty")
o.bind("SUPER + E", "Yazi", "ghostty -e yazi")
o.bind("SUPER + B", "Daily note", "obsidian 'obsidian://daily?vault=The%20Well'")
o.bind("SUPER + N", "Swap next window", "hyprctl dispatch swapnext")
o.bind("SUPER + R", "Reload configuration", "hyprctl reload")
o.bind("CTRL + grave", "Start dictation", "whisper-dictate-start")
o.bind("CTRL + grave", "Stop dictation", "whisper-dictate-stop", { release = true })
o.bind("SUPER + SHIFT + mouse:272", "Resize window", hl.dsp.window.resize(), { mouse = true })
