# Do not modify this file!  It was generated by 'nixos-generate-config'
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{
  config,
  lib,
  pkgs,
  modulesPath,
  ...
}: {
  imports = [
    (modulesPath + "/installer/scan/not-detected.nix")
  ];

  boot = {
    initrd = {
      availableKernelModules = [
        "nvme"
        "xhci_pci"
        "ahci"
        "usbhid"
        "usb_storage"
        "sd_mod"
      ];
      kernelModules = [];
    };
    kernelModules = [
      "kvm-amd"
      "i2c-dev"
    ]; # i2c-dev needed for ddcutil
    extraModulePackages = [];
  };

  fileSystems = {
    "/" = {
      device = "/dev/disk/by-uuid/07939a85-8044-4996-a897-fc94f5ccbe23";
      fsType = "btrfs";
      options = ["subvol=@"];
    };

    "/home" = {
      device = "/dev/disk/by-uuid/07939a85-8044-4996-a897-fc94f5ccbe23";
      fsType = "btrfs";
      options = ["subvol=@home"];
    };

    "/boot" = {
      device = "/dev/disk/by-uuid/E927-41AA";
      fsType = "vfat";
      options = [
        "fmask=0077"
        "dmask=0077"
      ];
    };

    "/run/media/nick/D" = {
      device = "/dev/disk/by-label/D";
      fsType = "ntfs";
      options = [
        "rw"
        "nofail"
      ];
    };

    "/run/media/nick/mac" = {
      device = "/dev/disk/by-uuid/5d102971-8000-437e-a4be-9dc145c26a65";
      fsType = "apfs";
      options = ["nofail"];
    };
  };

  swapDevices = [
    {device = "/dev/disk/by-uuid/4af6cab7-b974-4df4-8839-d38c38a26077";}
  ];

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.amd.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
